---
- name: Adicionando repositório para o VSCode
  become: true
  yum_repository:
    name: Code
    description: Visual Studio Code repo
    file: vscode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes

- name: Instalando o Visual Studio Code
  become: true
  dnf:
    name: code
    update_cache: yes
    state: present