---
- name: Incluindo arquivos de configuração
  include_tasks: "{{ task_file }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
      - "{{ ansible_distribution }}.yml"
  loop_control:
    loop_var: task_file

- name: Verificando a lista de Plugins Instalados
  shell: "code --list-extensions | tr '[:upper:]' '[:lower:]'"
  register: plugin_installed
  changed_when: False

- name: Instalando os Plugins para o VSCode
  shell: "code --install-extension {{ item }}"
  become: false
  with_items:
    - "{{ vscode_plugins }}"
  when: item | lower not in plugin_installed.stdout
  